#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TracNghiem")]
	public partial class LINQ_TracNghiemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKetQua(KetQua instance);
    partial void UpdateKetQua(KetQua instance);
    partial void DeleteKetQua(KetQua instance);
    partial void InserttblSV(tblSV instance);
    partial void UpdatetblSV(tblSV instance);
    partial void DeletetblSV(tblSV instance);
    partial void InserttblCauHoi(tblCauHoi instance);
    partial void UpdatetblCauHoi(tblCauHoi instance);
    partial void DeletetblCauHoi(tblCauHoi instance);
    partial void InserttblChiTietDeThi(tblChiTietDeThi instance);
    partial void UpdatetblChiTietDeThi(tblChiTietDeThi instance);
    partial void DeletetblChiTietDeThi(tblChiTietDeThi instance);
    partial void InserttblDapAn(tblDapAn instance);
    partial void UpdatetblDapAn(tblDapAn instance);
    partial void DeletetblDapAn(tblDapAn instance);
    partial void InserttblDeThi(tblDeThi instance);
    partial void UpdatetblDeThi(tblDeThi instance);
    partial void DeletetblDeThi(tblDeThi instance);
    #endregion
		
		public LINQ_TracNghiemDataContext() : 
				base(global::DAO.Properties.Settings.Default.TracNghiemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_TracNghiemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_TracNghiemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_TracNghiemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQ_TracNghiemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KetQua> KetQuas
		{
			get
			{
				return this.GetTable<KetQua>();
			}
		}
		
		public System.Data.Linq.Table<tblSV> tblSVs
		{
			get
			{
				return this.GetTable<tblSV>();
			}
		}
		
		public System.Data.Linq.Table<tblCauHoi> tblCauHois
		{
			get
			{
				return this.GetTable<tblCauHoi>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietDeThi> tblChiTietDeThis
		{
			get
			{
				return this.GetTable<tblChiTietDeThi>();
			}
		}
		
		public System.Data.Linq.Table<tblDapAn> tblDapAns
		{
			get
			{
				return this.GetTable<tblDapAn>();
			}
		}
		
		public System.Data.Linq.Table<tblDeThi> tblDeThis
		{
			get
			{
				return this.GetTable<tblDeThi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KetQua")]
	public partial class KetQua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDT;
		
		private string _MaSV;
		
		private System.Nullable<System.DateTime> _NgayThi;
		
		private System.Nullable<double> _Diem;
		
		private string _DapAN;
		
		private EntityRef<tblSV> _tblSV;
		
		private EntityRef<tblDeThi> _tblDeThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDTChanging(string value);
    partial void OnMaDTChanged();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnNgayThiChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThiChanged();
    partial void OnDiemChanging(System.Nullable<double> value);
    partial void OnDiemChanged();
    partial void OnDapANChanging(string value);
    partial void OnDapANChanged();
    #endregion
		
		public KetQua()
		{
			this._tblSV = default(EntityRef<tblSV>);
			this._tblDeThi = default(EntityRef<tblDeThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDT", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDT
		{
			get
			{
				return this._MaDT;
			}
			set
			{
				if ((this._MaDT != value))
				{
					if (this._tblDeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDTChanging(value);
					this.SendPropertyChanging();
					this._MaDT = value;
					this.SendPropertyChanged("MaDT");
					this.OnMaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					if (this._tblSV.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Float")]
		public System.Nullable<double> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAN", DbType="VarChar(500)")]
		public string DapAN
		{
			get
			{
				return this._DapAN;
			}
			set
			{
				if ((this._DapAN != value))
				{
					this.OnDapANChanging(value);
					this.SendPropertyChanging();
					this._DapAN = value;
					this.SendPropertyChanged("DapAN");
					this.OnDapANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSV_KetQua", Storage="_tblSV", ThisKey="MaSV", OtherKey="MaSV", IsForeignKey=true)]
		public tblSV tblSV
		{
			get
			{
				return this._tblSV.Entity;
			}
			set
			{
				tblSV previousValue = this._tblSV.Entity;
				if (((previousValue != value) 
							|| (this._tblSV.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSV.Entity = null;
						previousValue.KetQuas.Remove(this);
					}
					this._tblSV.Entity = value;
					if ((value != null))
					{
						value.KetQuas.Add(this);
						this._MaSV = value.MaSV;
					}
					else
					{
						this._MaSV = default(string);
					}
					this.SendPropertyChanged("tblSV");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDeThi_KetQua", Storage="_tblDeThi", ThisKey="MaDT", OtherKey="MaDeThi", IsForeignKey=true)]
		public tblDeThi tblDeThi
		{
			get
			{
				return this._tblDeThi.Entity;
			}
			set
			{
				tblDeThi previousValue = this._tblDeThi.Entity;
				if (((previousValue != value) 
							|| (this._tblDeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDeThi.Entity = null;
						previousValue.KetQuas.Remove(this);
					}
					this._tblDeThi.Entity = value;
					if ((value != null))
					{
						value.KetQuas.Add(this);
						this._MaDT = value.MaDeThi;
					}
					else
					{
						this._MaDT = default(string);
					}
					this.SendPropertyChanged("tblDeThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSV")]
	public partial class tblSV : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSV;
		
		private string _MatKhau;
		
		private string _HoTen;
		
		private System.Nullable<bool> _GioiTinh;
		
		private System.Nullable<int> _NamSinh;
		
		private EntitySet<KetQua> _KetQuas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSVChanging(string value);
    partial void OnMaSVChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnNamSinhChanging(System.Nullable<int> value);
    partial void OnNamSinhChanged();
    #endregion
		
		public tblSV()
		{
			this._KetQuas = new EntitySet<KetQua>(new Action<KetQua>(this.attach_KetQuas), new Action<KetQua>(this.detach_KetQuas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSV", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSV
		{
			get
			{
				return this._MaSV;
			}
			set
			{
				if ((this._MaSV != value))
				{
					this.OnMaSVChanging(value);
					this.SendPropertyChanging();
					this._MaSV = value;
					this.SendPropertyChanged("MaSV");
					this.OnMaSVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
		public System.Nullable<bool> GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Int")]
		public System.Nullable<int> NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSV_KetQua", Storage="_KetQuas", ThisKey="MaSV", OtherKey="MaSV")]
		public EntitySet<KetQua> KetQuas
		{
			get
			{
				return this._KetQuas;
			}
			set
			{
				this._KetQuas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.tblSV = this;
		}
		
		private void detach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.tblSV = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCauHoi")]
	public partial class tblCauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCH;
		
		private string _NoiDung;
		
		private EntitySet<tblChiTietDeThi> _tblChiTietDeThis;
		
		private EntitySet<tblDapAn> _tblDapAns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCHChanging(string value);
    partial void OnMaCHChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    #endregion
		
		public tblCauHoi()
		{
			this._tblChiTietDeThis = new EntitySet<tblChiTietDeThi>(new Action<tblChiTietDeThi>(this.attach_tblChiTietDeThis), new Action<tblChiTietDeThi>(this.detach_tblChiTietDeThis));
			this._tblDapAns = new EntitySet<tblDapAn>(new Action<tblDapAn>(this.attach_tblDapAns), new Action<tblDapAn>(this.detach_tblDapAns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCH", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCH
		{
			get
			{
				return this._MaCH;
			}
			set
			{
				if ((this._MaCH != value))
				{
					this.OnMaCHChanging(value);
					this.SendPropertyChanging();
					this._MaCH = value;
					this.SendPropertyChanged("MaCH");
					this.OnMaCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(200)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCauHoi_tblChiTietDeThi", Storage="_tblChiTietDeThis", ThisKey="MaCH", OtherKey="MaCH")]
		public EntitySet<tblChiTietDeThi> tblChiTietDeThis
		{
			get
			{
				return this._tblChiTietDeThis;
			}
			set
			{
				this._tblChiTietDeThis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCauHoi_tblDapAn", Storage="_tblDapAns", ThisKey="MaCH", OtherKey="MaCH")]
		public EntitySet<tblDapAn> tblDapAns
		{
			get
			{
				return this._tblDapAns;
			}
			set
			{
				this._tblDapAns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietDeThis(tblChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.tblCauHoi = this;
		}
		
		private void detach_tblChiTietDeThis(tblChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.tblCauHoi = null;
		}
		
		private void attach_tblDapAns(tblDapAn entity)
		{
			this.SendPropertyChanging();
			entity.tblCauHoi = this;
		}
		
		private void detach_tblDapAns(tblDapAn entity)
		{
			this.SendPropertyChanging();
			entity.tblCauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietDeThi")]
	public partial class tblChiTietDeThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDT;
		
		private string _MaCH;
		
		private System.Nullable<int> _ThuTu;
		
		private EntityRef<tblCauHoi> _tblCauHoi;
		
		private EntityRef<tblDeThi> _tblDeThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDTChanging(string value);
    partial void OnMaDTChanged();
    partial void OnMaCHChanging(string value);
    partial void OnMaCHChanged();
    partial void OnThuTuChanging(System.Nullable<int> value);
    partial void OnThuTuChanged();
    #endregion
		
		public tblChiTietDeThi()
		{
			this._tblCauHoi = default(EntityRef<tblCauHoi>);
			this._tblDeThi = default(EntityRef<tblDeThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDT", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDT
		{
			get
			{
				return this._MaDT;
			}
			set
			{
				if ((this._MaDT != value))
				{
					if (this._tblDeThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDTChanging(value);
					this.SendPropertyChanging();
					this._MaDT = value;
					this.SendPropertyChanged("MaDT");
					this.OnMaDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCH", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCH
		{
			get
			{
				return this._MaCH;
			}
			set
			{
				if ((this._MaCH != value))
				{
					if (this._tblCauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCHChanging(value);
					this.SendPropertyChanging();
					this._MaCH = value;
					this.SendPropertyChanged("MaCH");
					this.OnMaCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int")]
		public System.Nullable<int> ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCauHoi_tblChiTietDeThi", Storage="_tblCauHoi", ThisKey="MaCH", OtherKey="MaCH", IsForeignKey=true)]
		public tblCauHoi tblCauHoi
		{
			get
			{
				return this._tblCauHoi.Entity;
			}
			set
			{
				tblCauHoi previousValue = this._tblCauHoi.Entity;
				if (((previousValue != value) 
							|| (this._tblCauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCauHoi.Entity = null;
						previousValue.tblChiTietDeThis.Remove(this);
					}
					this._tblCauHoi.Entity = value;
					if ((value != null))
					{
						value.tblChiTietDeThis.Add(this);
						this._MaCH = value.MaCH;
					}
					else
					{
						this._MaCH = default(string);
					}
					this.SendPropertyChanged("tblCauHoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDeThi_tblChiTietDeThi", Storage="_tblDeThi", ThisKey="MaDT", OtherKey="MaDeThi", IsForeignKey=true)]
		public tblDeThi tblDeThi
		{
			get
			{
				return this._tblDeThi.Entity;
			}
			set
			{
				tblDeThi previousValue = this._tblDeThi.Entity;
				if (((previousValue != value) 
							|| (this._tblDeThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDeThi.Entity = null;
						previousValue.tblChiTietDeThis.Remove(this);
					}
					this._tblDeThi.Entity = value;
					if ((value != null))
					{
						value.tblChiTietDeThis.Add(this);
						this._MaDT = value.MaDeThi;
					}
					else
					{
						this._MaDT = default(string);
					}
					this.SendPropertyChanged("tblDeThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDapAn")]
	public partial class tblDapAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCH;
		
		private string _MaTL;
		
		private string _NoiDungTL;
		
		private System.Nullable<bool> _DapAn;
		
		private EntityRef<tblCauHoi> _tblCauHoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCHChanging(string value);
    partial void OnMaCHChanged();
    partial void OnMaTLChanging(string value);
    partial void OnMaTLChanged();
    partial void OnNoiDungTLChanging(string value);
    partial void OnNoiDungTLChanged();
    partial void OnDapAnChanging(System.Nullable<bool> value);
    partial void OnDapAnChanged();
    #endregion
		
		public tblDapAn()
		{
			this._tblCauHoi = default(EntityRef<tblCauHoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCH", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCH
		{
			get
			{
				return this._MaCH;
			}
			set
			{
				if ((this._MaCH != value))
				{
					if (this._tblCauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCHChanging(value);
					this.SendPropertyChanging();
					this._MaCH = value;
					this.SendPropertyChanged("MaCH");
					this.OnMaCHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTL", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTL
		{
			get
			{
				return this._MaTL;
			}
			set
			{
				if ((this._MaTL != value))
				{
					this.OnMaTLChanging(value);
					this.SendPropertyChanging();
					this._MaTL = value;
					this.SendPropertyChanged("MaTL");
					this.OnMaTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungTL", DbType="NVarChar(200)")]
		public string NoiDungTL
		{
			get
			{
				return this._NoiDungTL;
			}
			set
			{
				if ((this._NoiDungTL != value))
				{
					this.OnNoiDungTLChanging(value);
					this.SendPropertyChanging();
					this._NoiDungTL = value;
					this.SendPropertyChanged("NoiDungTL");
					this.OnNoiDungTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAn", DbType="Bit")]
		public System.Nullable<bool> DapAn
		{
			get
			{
				return this._DapAn;
			}
			set
			{
				if ((this._DapAn != value))
				{
					this.OnDapAnChanging(value);
					this.SendPropertyChanging();
					this._DapAn = value;
					this.SendPropertyChanged("DapAn");
					this.OnDapAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCauHoi_tblDapAn", Storage="_tblCauHoi", ThisKey="MaCH", OtherKey="MaCH", IsForeignKey=true)]
		public tblCauHoi tblCauHoi
		{
			get
			{
				return this._tblCauHoi.Entity;
			}
			set
			{
				tblCauHoi previousValue = this._tblCauHoi.Entity;
				if (((previousValue != value) 
							|| (this._tblCauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCauHoi.Entity = null;
						previousValue.tblDapAns.Remove(this);
					}
					this._tblCauHoi.Entity = value;
					if ((value != null))
					{
						value.tblDapAns.Add(this);
						this._MaCH = value.MaCH;
					}
					else
					{
						this._MaCH = default(string);
					}
					this.SendPropertyChanged("tblCauHoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDeThi")]
	public partial class tblDeThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDeThi;
		
		private string _TenDT;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private EntitySet<KetQua> _KetQuas;
		
		private EntitySet<tblChiTietDeThi> _tblChiTietDeThis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDeThiChanging(string value);
    partial void OnMaDeThiChanged();
    partial void OnTenDTChanging(string value);
    partial void OnTenDTChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    #endregion
		
		public tblDeThi()
		{
			this._KetQuas = new EntitySet<KetQua>(new Action<KetQua>(this.attach_KetQuas), new Action<KetQua>(this.detach_KetQuas));
			this._tblChiTietDeThis = new EntitySet<tblChiTietDeThi>(new Action<tblChiTietDeThi>(this.attach_tblChiTietDeThis), new Action<tblChiTietDeThi>(this.detach_tblChiTietDeThis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDeThi", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDeThi
		{
			get
			{
				return this._MaDeThi;
			}
			set
			{
				if ((this._MaDeThi != value))
				{
					this.OnMaDeThiChanging(value);
					this.SendPropertyChanging();
					this._MaDeThi = value;
					this.SendPropertyChanged("MaDeThi");
					this.OnMaDeThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDT", DbType="NVarChar(100)")]
		public string TenDT
		{
			get
			{
				return this._TenDT;
			}
			set
			{
				if ((this._TenDT != value))
				{
					this.OnTenDTChanging(value);
					this.SendPropertyChanging();
					this._TenDT = value;
					this.SendPropertyChanged("TenDT");
					this.OnTenDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDeThi_KetQua", Storage="_KetQuas", ThisKey="MaDeThi", OtherKey="MaDT")]
		public EntitySet<KetQua> KetQuas
		{
			get
			{
				return this._KetQuas;
			}
			set
			{
				this._KetQuas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDeThi_tblChiTietDeThi", Storage="_tblChiTietDeThis", ThisKey="MaDeThi", OtherKey="MaDT")]
		public EntitySet<tblChiTietDeThi> tblChiTietDeThis
		{
			get
			{
				return this._tblChiTietDeThis;
			}
			set
			{
				this._tblChiTietDeThis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.tblDeThi = this;
		}
		
		private void detach_KetQuas(KetQua entity)
		{
			this.SendPropertyChanging();
			entity.tblDeThi = null;
		}
		
		private void attach_tblChiTietDeThis(tblChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.tblDeThi = this;
		}
		
		private void detach_tblChiTietDeThis(tblChiTietDeThi entity)
		{
			this.SendPropertyChanging();
			entity.tblDeThi = null;
		}
	}
}
#pragma warning restore 1591
